# /etc/freeradius/3.0/users — SERVIDOM S.A. (Empresa 3)
# Autenticación Centralizada RADIUS para los 6 Integrantes de TI

# 1. Cristopher Navarro (Director General de TI)
cnavarro    Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Cristopher Navarro (Director TI)"

2025-0720   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Cristopher Navarro (2025-0720)"

# 2. Justin Luciano (Servicios Digitales & Finanzas)
jluciano    Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Justin Luciano (Finanzas & Web)"

2025-0054   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Justin Luciano (2025-0054)"

# 3. Gregory Morel (Especialista LAN Santo Domingo)
gmorel      Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Gregory Morel (LAN Core SD)"

2025-0035   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Gregory Morel (2025-0035)"

# 4. Sayid Cabral (Ingeniero Infraestructura CECOMPE Liaison)
scabral     Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Sayid Cabral (CECOMPE Liaison)"

2025-1364   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Sayid Cabral (2025-1364)"

# 5. Yadhier López (Administrador DataCenter Santiago)
ylopez      Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Yadhier Lopez (DataCenter STGO)"

2025-1365   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Yadhier Lopez (2025-1365)"

# 6. Enmanuel Mendez (Especialista WAN & VPN La Romana)
emendez     Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Enmanuel Mendez (WAN & VPN LR)"

2025-0753   Cleartext-Password := "Servidom2026!"
            Huawei-Exec-Privilege = 15,
            Reply-Message = "Bienvenido Enmanuel Mendez (2025-0753)"
