# /etc/postfix/main.cf & vmailbox — SERVIDOM S.A. (Empresa 3)
# Configuración del Servidor de Correo Institucional @servidom.com.do

myhostname = mail.servidom.com.do
mydomain = servidom.com.do
myorigin = $mydomain
inet_interfaces = all
inet_protocols = ipv4
mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
mynetworks = 127.0.0.0/8 192.168.0.0/16 19.0.0.0/24

# Buzones de correo de los 6 integrantes de la Empresa 3:
# cnavarro@servidom.com.do  -> Cristopher Navarro (2025-0720)
# jluciano@servidom.com.do  -> Justin Luciano (2025-0054)
# gmorel@servidom.com.do    -> Gregory Morel (2025-0035)
# scabral@servidom.com.do   -> Sayid Cabral (2025-1364)
# ylopez@servidom.com.do    -> Yadhier López (2025-1365)
# emendez@servidom.com.do   -> Enmanuel Mendez (2025-0753)
